"""
代码生成器模块（基于 CodeTransformer V2.0）
不再依赖 Jinja2 模板，而是使用基于 LLM 的 AST 变换引擎
"""
import json
import logging
from pathlib import Path
from typing import List, Dict, Any
from datetime import datetime

from modules.code_transformer import CodeTransformer
from modules.dependency_validator import DependencyValidator

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class CodeGenerator:
    """基于 CodeTransformer 的代码生成器 V2.0"""

    def __init__(self, plan_path: str):
        """
        初始化代码生成器

        Args:
            plan_path: project_plan.json 路径
        """
        self.plan_path = Path(plan_path)

        if not self.plan_path.exists():
            raise FileNotFoundError(f"项目规划文件不存在: {plan_path}")

        with open(self.plan_path, 'r', encoding='utf-8') as f:
            self.plan = json.load(f)

        self.project_name = self.plan.get("project_name", "未命名项目")

        # V2.0 核心组件
        # 1. 变换引擎：负责业务逻辑迁移和物理混淆
        self.transformer = CodeTransformer(self.plan)
        # 2. 依赖验证器：负责清理非法引包
        self.validator = DependencyValidator()

        logger.info(f"CodeGenerator V2.0 初始化: {self.project_name}")
        logger.info(f"目标语言: {self.transformer.target_language}")

    def generate_all(self, output_dir: str) -> List[str]:
        """
        执行完整代码生成流程
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        all_files = []

        try:
            logger.info("开始生成核心代码 (CodeTransformer)...")

            # 1. 调用变换引擎生成核心代码
            # 注意：transform_seed_to_project 内部会处理文件写入
            code_files = self.transformer.transform_seed_to_project(output_path)

            # 2. 依赖校验与清洗
            logger.info("开始执行依赖校验与清洗...")
            target_lang = self.transformer.target_language
            validated_files = []

            for file_path_str in code_files:
                path = Path(file_path_str)
                if not path.exists():
                    continue

                try:
                    content = path.read_text(encoding='utf-8')
                    # 清洗依赖
                    cleaned_content = self.validator.validate_and_clean(content, target_lang)

                    # 只有当内容发生变化时才写回，减少IO
                    if cleaned_content != content:
                        path.write_text(cleaned_content, encoding='utf-8')
                        logger.debug(f"已清洗文件: {path.name}")

                    validated_files.append(str(path))
                except Exception as e:
                    logger.error(f"校验文件失败 {path}: {e}")
                    # 即使校验失败也保留文件，但在列表里记录
                    validated_files.append(str(path))

            all_files.extend(validated_files)

            # 3. 生成配置文件 (requirements.txt, pom.xml 等)
            logger.info("生成项目配置文件...")
            config_files = self._generate_config_files(output_path, target_lang)
            all_files.extend(config_files)

            logger.info(f"项目生成完成，共 {len(all_files)} 个文件")
            return all_files

        except RuntimeError as e:
            # 质量闸门等硬错误应向上抛出，阻止后续文档/PDF继续执行。
            logger.error(f"代码生成流程硬失败: {e}", exc_info=True)
            raise
        except Exception as e:
            logger.error(f"代码生成流程发生严重错误: {e}", exc_info=True)
            # 在严重错误时返回已生成的文件列表，避免完全失败
            return all_files

    def _generate_config_files(self, output_dir: Path, language: str) -> List[str]:
        """根据目标语言生成对应的包管理配置"""
        files = []
        language = language.lower()

        try:
            if language == "python":
                # 生成 requirements.txt
                content = self._get_python_requirements()
                path = output_dir / "requirements.txt"
                path.write_text(content, encoding='utf-8')
                files.append(str(path))

            elif language == "java":
                # 生成 pom.xml
                content = self._get_java_pom()
                path = output_dir / "pom.xml"
                path.write_text(content, encoding='utf-8')
                files.append(str(path))

            elif language in ["node.js", "nodejs", "javascript"]:
                # 生成 package.json
                content = self._get_nodejs_package()
                path = output_dir / "package.json"
                path.write_text(content, encoding='utf-8')
                files.append(str(path))

            # 4. 生成 DevOps 配置文件
            devops_files = self._generate_devops_files(output_dir, language)
            files.extend(devops_files)

            # 5. 生成通用 README
            readme_path = output_dir / "README.md"
            readme_content = f"""# {self.project_name}

Generated by AI Software Generator V2.0

## Project Info
- **Project Name**: {self.project_name}
- **Language**: {language}
- **Generated At**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Getting Started

### Prerequisites
See generated configuration files.

### Installation
Run the setup script or install dependencies manually.
"""
            readme_path.write_text(readme_content, encoding='utf-8')
            files.append(str(readme_path))

        except Exception as e:
            logger.error(f"生成配置文件失败: {e}")

        return files

    def _get_python_requirements(self) -> str:
        """生成 Python 依赖列表"""
        return """fastapi>=0.68.0
uvicorn>=0.15.0
sqlalchemy>=1.4.0
pydantic>=1.8.0
python-dotenv>=0.19.0
requests>=2.26.0
"""

    def _get_java_pom(self) -> str:
        """生成 Maven POM 文件"""
        group_id = "com." + self.project_name.lower().replace(' ', '.')
        artifact_id = self.project_name.lower().replace(' ', '-')

        return f"""<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>{group_id}</groupId>
    <artifactId>{artifact_id}</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>{self.project_name}</name>
    <description>Generated project for {self.project_name}</description>

    <properties>
        <java.version>17</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
"""

    def _get_nodejs_package(self) -> str:
        """生成 Node.js package.json"""
        return json.dumps({
            "name": self.project_name.lower().replace(' ', '-'),
            "version": "1.0.0",
            "description": f"Generated project for {self.project_name}",
            "main": "index.js",
            "scripts": {
                "start": "node index.js",
                "dev": "nodemon index.js"
            },
            "dependencies": {
                "express": "^4.17.1",
                "mongoose": "^6.0.0",
                "cors": "^2.8.5",
                "dotenv": "^10.0.0"
            },
            "devDependencies": {
                "nodemon": "^2.0.12"
            }
        }, indent=2)

    def _generate_devops_files(self, output_dir: Path, language: str) -> List[str]:
        """
        生成 DevOps 配置文件 (Dockerfile, docker-compose.yml, .gitignore, .env.example, CI)
        让生成的项目更接近真实项目结构
        """
        files = []
        language = language.lower()

        try:
            # 1. 生成 Dockerfile
            dockerfile_content = self._get_dockerfile(language)
            dockerfile_path = output_dir / "Dockerfile"
            dockerfile_path.write_text(dockerfile_content, encoding='utf-8')
            files.append(str(dockerfile_path))

            # 2. 生成 docker-compose.yml
            compose_content = self._get_docker_compose(language)
            compose_path = output_dir / "docker-compose.yml"
            compose_path.write_text(compose_content, encoding='utf-8')
            files.append(str(compose_path))

            # 3. 生成 .gitignore
            gitignore_content = self._get_gitignore(language)
            gitignore_path = output_dir / ".gitignore"
            gitignore_path.write_text(gitignore_content, encoding='utf-8')
            files.append(str(gitignore_path))

            # 4. 生成 .env.example
            env_content = self._get_env_example(language)
            env_path = output_dir / ".env.example"
            env_path.write_text(env_content, encoding='utf-8')
            files.append(str(env_path))

            # 5. 生成 GitHub Actions CI
            workflows_dir = output_dir / ".github" / "workflows"
            workflows_dir.mkdir(parents=True, exist_ok=True)
            ci_content = self._get_github_ci(language)
            ci_path = workflows_dir / "ci.yml"
            ci_path.write_text(ci_content, encoding='utf-8')
            files.append(str(ci_path))

            logger.info(f"DevOps 配置文件生成完成，共 {len(files)} 个文件")

        except Exception as e:
            logger.error(f"生成 DevOps 配置文件失败: {e}")

        return files

    def _get_dockerfile(self, language: str) -> str:
        """生成多阶段构建 Dockerfile"""
        if language == "python":
            return '''# 多阶段构建 Dockerfile
# Stage 1: 构建阶段
FROM python:3.11-slim as builder

WORKDIR /app

# 安装依赖
COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

# Stage 2: 运行阶段
FROM python:3.11-slim

WORKDIR /app

# 从构建阶段复制依赖
COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH

# 复制应用代码
COPY . .

# 创建非 root 用户
RUN useradd -m appuser && chown -R appuser:appuser /app
USER appuser

# 暴露端口
EXPOSE 8000

# 健康检查
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD curl -f http://localhost:8000/health || exit 1

# 启动命令
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
'''
        elif language == "java":
            return '''# 多阶段构建 Dockerfile
# Stage 1: 构建阶段
FROM maven:3.9-eclipse-temurin-17 as builder

WORKDIR /app

# 复制 pom.xml 并下载依赖（利用 Docker 缓存）
COPY pom.xml .
RUN mvn dependency:go-offline -B

# 复制源码并构建
COPY src ./src
RUN mvn package -DskipTests -B

# Stage 2: 运行阶段
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# 从构建阶段复制 JAR
COPY --from=builder /app/target/*.jar app.jar

# 创建非 root 用户
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

# 暴露端口
EXPOSE 8080

# JVM 参数优化
ENV JAVA_OPTS="-Xms256m -Xmx512m -XX:+UseG1GC"

# 健康检查
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1

# 启动命令
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
'''
        else:  # Node.js 等其他语言
            return '''# 多阶段构建 Dockerfile
# Stage 1: 构建阶段
FROM node:18-alpine as builder

WORKDIR /app

# 复制 package 文件并安装依赖
COPY package*.json ./
RUN npm ci --only=production

# Stage 2: 运行阶段
FROM node:18-alpine

WORKDIR /app

# 从构建阶段复制 node_modules
COPY --from=builder /app/node_modules ./node_modules
COPY . .

# 创建非 root 用户
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

# 暴露端口
EXPOSE 3000

# 健康检查
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1

# 启动命令
CMD ["node", "index.js"]
'''

    def _get_docker_compose(self, language: str) -> str:
        """生成 docker-compose.yml"""
        app_port = "8000" if language == "python" else ("8080" if language == "java" else "3000")

        return f'''version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${{PROJECT_NAME:-app}}
    restart: unless-stopped
    ports:
      - "${{APP_PORT:-{app_port}}}:{app_port}"
    environment:
      - DATABASE_URL=${{DATABASE_URL:-mysql://root:password@db:3306/appdb}}
      - REDIS_URL=${{REDIS_URL:-redis://redis:6379/0}}
      - LOG_LEVEL=${{LOG_LEVEL:-INFO}}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
    volumes:
      - ./logs:/app/logs

  db:
    image: mysql:8.0
    container_name: ${{PROJECT_NAME:-app}}-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${{MYSQL_ROOT_PASSWORD:-password}}
      MYSQL_DATABASE: ${{MYSQL_DATABASE:-appdb}}
      MYSQL_USER: ${{MYSQL_USER:-appuser}}
      MYSQL_PASSWORD: ${{MYSQL_PASSWORD:-apppass}}
    ports:
      - "${{DB_PORT:-3306}}:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: ${{PROJECT_NAME:-app}}-redis
    restart: unless-stopped
    ports:
      - "${{REDIS_PORT:-6379}}:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
'''

    def _get_gitignore(self, language: str) -> str:
        """生成 .gitignore"""
        common = '''# 通用忽略规则
.env
.env.local
*.log
logs/
tmp/
temp/
.DS_Store
Thumbs.db

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# 测试覆盖率
coverage/
htmlcov/
.coverage
'''
        if language == "python":
            return common + '''
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual Environment
venv/
ENV/
env/
.venv/

# Pytest
.pytest_cache/
.tox/
.nox/

# mypy
.mypy_cache/
'''
        elif language == "java":
            return common + '''
# Java
*.class
*.jar
*.war
*.ear
*.nar

# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties
dependency-reduced-pom.xml
buildNumber.properties
.mvn/timing.properties
.mvn/wrapper/maven-wrapper.jar

# Gradle
.gradle/
build/
!gradle/wrapper/gradle-wrapper.jar

# Eclipse
.classpath
.project
.settings/

# IntelliJ
*.iml
*.ipr
*.iws
out/
'''
        else:  # Node.js
            return common + '''
# Node.js
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.npm
.yarn-integrity

# Build
dist/
build/
.next/
.nuxt/

# TypeScript
*.tsbuildinfo
'''

    def _get_env_example(self, language: str) -> str:
        """生成 .env.example"""
        return '''# 应用配置
APP_NAME=MyApplication
APP_ENV=development
APP_DEBUG=true
APP_PORT=8000

# 数据库配置
DATABASE_URL=mysql://root:password@localhost:3306/appdb
DB_HOST=localhost
DB_PORT=3306
DB_NAME=appdb
DB_USER=root
DB_PASSWORD=password

# Redis 配置
REDIS_URL=redis://localhost:6379/0
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=

# 日志配置
LOG_LEVEL=INFO
LOG_FILE=logs/app.log

# JWT 配置
JWT_SECRET=your-super-secret-key-change-in-production
JWT_EXPIRES_IN=86400

# 第三方服务
# SMTP_HOST=smtp.example.com
# SMTP_PORT=587
# SMTP_USER=
# SMTP_PASSWORD=

# Docker Compose
PROJECT_NAME=myapp
MYSQL_ROOT_PASSWORD=password
MYSQL_DATABASE=appdb
MYSQL_USER=appuser
MYSQL_PASSWORD=apppass
'''

    def _get_github_ci(self, language: str) -> str:
        """生成 GitHub Actions CI 配置"""
        if language == "python":
            return '''name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpassword
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      env:
        DATABASE_URL: mysql://root:testpassword@localhost:3306/testdb
      run: |
        pytest --cov=. --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install linters
      run: pip install flake8 black isort

    - name: Run linters
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        black --check .
        isort --check-only .

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t app:${{ github.sha }} .
'''
        elif language == "java":
            return '''name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpassword
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run tests
      run: mvn test -B

    - name: Generate coverage report
      run: mvn jacoco:report

    - name: Upload coverage
      uses: codecov/codecov-action@v3

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn package -DskipTests -B

    - name: Build Docker image
      run: docker build -t app:${{ github.sha }} .
'''
        else:  # Node.js
            return '''name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test -- --coverage

    - name: Upload coverage
      uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t app:${{ github.sha }} .
'''


def generate_code_from_plan(plan_path: str, output_dir: str) -> List[str]:
    """
    便捷函数：从项目规划生成代码

    Args:
        plan_path: project_plan.json 路径
        output_dir: 输出目录

    Returns:
        生成的文件路径列表
    """
    generator = CodeGenerator(plan_path)
    return generator.generate_all(output_dir)
